#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -arch x86_64 -O3 -DL_ENDIAN -DMD32_REG_T=int -Wall"
  #define PLATFORM "darwin64-x86_64-cc"
  #define DATE "Sat Jul 31 01:57:27 PDT 2010"
#endif
